name: Build and Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "BUILD_PATH=path/to/build" >> $GITHUB_ENV
          
      - name: Download files
        run: |
          ./download_files.sh

      - name: Build container
        run: |
          ./build_container.sh

      - name: Run tests
        run: |
          ./do_tests.sh

