name: Test Artifact Upload

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create artifact
        run: echo "Hello, world!" > artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: artifact.txt
